### ISSUE TITLE
change date formatting?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [tigercosmos/node-color-log#12]
I find the format very hard to read, how to change?

**Comment by hp8wvvvgnj6asjm7** [comment]
as well as timezone

**Comment by tigercosmos** [comment]
@hp8wvvvgnj6asjm7  this is the standard format to present the time. What is the format you are looking for?

**Comment by pierresh** [comment]
An option to see the current local time would be more convenient.

**Comment by tigercosmos** [comment]
@pierresh Would you like to improve it with a PR?

**Comment by pierresh** [comment]
Actually, now I use **dayjs()** like this:

```js
logger.setDate(() => {
	return dayjs().format('YYYY-MM-DD HH:mm:ss');
});
