### ISSUE TITLE
can't we make this a winston transporter?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [tigercosmos/node-color-log#14]

**Comment by tigercosmos** [comment]
@hp8wvvvgnj6asjm7  I don't get your point. Could you explain more?
IMO, this is just a lightweight logger, which is very different from Winston (It's a big monster)

**Comment by hp8wvvvgnj6asjm7** [comment]
I found it really difficult and annoying to deal with Winston and custom colors. This package has all the color modes and all one can ask for. I think many people would use this on top of Winston as a formatter.

Yes Winston is a monster, but it is also not the best to use multiple logging packages in bigger projects, some can end up with file loggers and color loggers and log exporters, but Winston can do all of them.

**Comment by hp8wvvvgnj6asjm7** [comment]
I'm just talking about the coloring stuff from your package but having these inside Winston as a plugin would be great.

**Comment by tigercosmos** [comment]
Well, I wrote this just because I think Winston is hard to use as well. Anyway, hope you enjoy this library  :)
