### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by jollyjerr** [tigercosmos/node-color-log#15]
Hey! I could not find any types for this project at `@types/node-color-log`

Would you be interested in typescript support? I'm willing to tackle it but I won't if you are not interested.

**Comment by tigercosmos** [comment]
@jollyjerr  Please help. Thanks a lot! :)

**Comment by tigercosmos** [comment]
I think it would be fine if we have a `.d.ts` file? Could you help create a PR?

**Comment by jollyjerr** [comment]
@tigercosmos sounds perfect. I'll submit a PR sometime soon!
