### ISSUE TITLE
Logger.log() enhance 

### ISSUE THREAD

**Issue by tigercosmos** [tigercosmos/node-color-log#2]
I want to extend it as:
```
logger.log('some message').color('red').feature('bold');
```
something like this.

**Comment by khalfella** [comment]
How about you use change the order like
`logger.color('red').feature('bold').log('some message').;`

**Comment by tigercosmos** [comment]
Color and feature are attributes, and we usually put setter after main function, I thought.
But anyway, that would be able to implement as well in the future. (Both orders are valid)

**Comment by tigercosmos** [comment]
done with `1.0.0`
