### ISSUE TITLE
4 times of 1 log

### ISSUE THREAD

**Issue by CrazyFlasher** [tigercosmos/node-color-log#20]
I call logger.info once, but receive result 4 lines of INFO
`logger.info("Manually defined classes: ", clazz.name);`
![image](https://user-images.githubusercontent.com/1607138/147357063-5b38674b-3ddd-456d-9f8f-c367787b16bc.png)

**Comment by tigercosmos** [comment]
@CrazyFlasher could you provide the system information. I knew this issue only happening on certain systems.

**Comment by CrazyFlasher** [comment]
Using **TypeScript** 4.4.3
```
{
  "compilerOptions": {
    "declaration": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "sourceMap": true,
    "target": "es2019",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "outDir": "./dist",
    "noImplicitOverride": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```
Running with **nodejs** v14.18.1
![image](https://user-images.githubusercontent.com/1607138/147362006-67d0981a-a0b9-4d39-8bd9-ce6f895f466b.png)

**Comment by CrazyFlasher** [comment]
Btw: it's easy to reproduce on https://codesandbox.io/

**Comment by lordslair** [comment]
I just started to use this module, and I noticed I have the same issue.
Is there any known workaround or configuration to fix this behaviour ?

**Comment by tigercosmos** [comment]
probably fixed in https://github.com/tigercosmos/node-color-log/commit/4a4f293312036e20fac645745a8a8d616ee29fb9
