### ISSUE TITLE
The system should use `console.error` instead of `console.log` for everything except `log()` messages

### ISSUE THREAD

**Issue by trevor-vaughan** [tigercosmos/node-color-log#28]
When you are using this library along with command pipes, you really need to be able to pull the debug statements away from the output.

The easiest way that I could think of doing this is to use `console.error` instead of `console.log` for everything except `log()` messages.

It would be great to be able to pass in file descriptors to use during configuration.

**Comment by tigercosmos** [comment]
@trevor-vaughan  I agree. I am very welcome to accept a PR for this.

**Comment by tigercosmos** [comment]
it's been a long time, and now I can announce the default output is stderr now.

**Comment by bkniffler** [comment]
<img width="660" alt="Bildschirmfoto 2024-03-17 um 09 34 33" src="https://github.com/tigercosmos/node-color-log/assets/4349324/7bf7f620-805b-48e8-9f63-3cea75e32eaa">

Any chance we could add a switch to use `log`? E.g. `wrangler dev` for cloudflare will show logs like this now.

**Comment by tigercosmos** [comment]
@bkniffler  yes, I think we can have a flag for it.  maybe a function call `logger.setOuptutStdout()`? and modify [`_print()`](https://github.com/tigercosmos/node-color-log/blob/7ced8b143b8939f1a288645285c6729b38dd4737/index.js#L346) based on the flag. A better solution should introduce a setup configuration when we launch the logger, but that might be too much work. I am fine with a easy and short method. If you have time, a PR is welcome.
