### ISSUE TITLE
verify the test output

### ISSUE THREAD

**Issue by tigercosmos** [tigercosmos/node-color-log#33]
currently, CI only generates the output and doesn't verify the output content.

**Comment by Link1515** [comment]
Hello @tigercosmos , I would like to work on this issue. My current idea is to use the `lastCommand` property to verify the output content.

ex:
```javascript
test('blue and italic.', () => {
    logger.color('blue').italic().log('blue and italic.');
    
    expect(logger.lastCommand).toBe('\x1b[34m\x1b[3mblue and italic.\x1b[0m');
});
```

However, I found that only the `log()` method saves the `lastCommand`, which causes other methods (such as `fontColorLog()`, `bgColorLog()`, and `colorLog()`) to be unable to verify the output.

Could I also save the `lastCommand` in these methods? Or do you have any other suggestions?

**Comment by tigercosmos** [comment]
@Link1515  sounds good, please go ahead. Using `lastCommand` for all methods should be fine. Feel free to ask questions at any time.
