### ISSUE TITLE
support file record

### ISSUE THREAD

**Issue by tigercosmos** [tigercosmos/node-color-log#4]
It should be able to save the log in file

**Comment by JoCat** [comment]
@tigercosmos it is possible to implement saving input to a file, but only in node.js environment
The question is that judging by the name node-color-log library is designed for node.js, but its description says the following "... logger for NodeJS and browsers". So now the question is, should I try to make an additional implementation for node.js with the ability to save to a file or do it in the current one while ignoring browser compatibility?

**Comment by tigercosmos** [comment]
@JoCat  yes, you can do that. Node.js is the first priority.

**Comment by tigercosmos** [comment]
done https://github.com/tigercosmos/node-color-log/commit/4a4f293312036e20fac645745a8a8d616ee29fb9
